### ISSUE TITLE
Ascom Connection

### ISSUE THREAD

**Issue by anthtone** [juanmb/ArduinoDomeController#1]
Hi

I noticed that you have a python file for Maxdomeii.py at the root level.  Is this used to connect into Ascom?

Where you able to interface your arduino boards into ascom?

Thank you in advance.

**Comment by juanmb** [comment]
Hi,
The python script you mentioned is only for testing the board by sending some commands.
I didn't test the setup under ASCOM (I don't have any windows computer around), but it should work, because the protocol is the one used by the original Maxdome II.
